/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AliasMoreOptions: typeof import('./src/components/AliasMoreOptions.vue')['default']
    ApiKeySetting: typeof import('./src/components/ApiKeySetting.vue')['default']
    AppSettings: typeof import('./src/components/AppSettings.vue')['default']
    ExpandTransition: typeof import('./src/components/ExpandTransition.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    MainPage: typeof import('./src/components/MainPage.vue')['default']
    NewAliasResult: typeof import('./src/components/NewAliasResult.vue')['default']
    ReverseAlias: typeof import('./src/components/ReverseAlias.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfHostSetting: typeof import('./src/components/SelfHostSetting.vue')['default']
    SlHeader: typeof import('./src/components/SlHeader.vue')['default']
    SplashScreen: typeof import('./src/components/SplashScreen.vue')['default']
    TextareaAutosize: typeof import('./src/components/TextareaAutosize.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
